### ISSUE TITLE
First Person Mod?

### ISSUE THREAD

**Issue by Xaident** [rbasamoyai/industrialwarfare#50]
Okay, this is not a mod bug, but it would be cool if it could be fixed.
The problem is that while using the weapon, the second layer of the skin is displayed on the screen.

Can this be fixed please?
![view](https://user-images.githubusercontent.com/110777865/183298271-4ca9d947-d63d-4cca-a476-a92f3c9b1bee.png)

**Comment by rbasamoyai** [comment]
This project is currently toeing the line between "on break" and "shelved"; no active development is taking place.
